### ISSUE TITLE
Error in darko-serve watch 

### ISSUE THREAD

**Issue by brianmacdonald** [dotnil/darko#7]
I receive the following error when using darko-serve -w in Cygwin in Windows 7
```javascript
path.js:204
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at FSWatcher.<anonymous> (D:\Workspaces\node_modules\darko\bin\darko-serve:191:22)
    at FSWatcher.emit (events.js:98:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1044:12)
```

The issue seems to be that the filename argument for watch is not supported on every platform.
See: http://nodejs.org/docs/latest/api/fs.html#fs_filename_argument

**Comment by dotnil** [comment]
Yeah, currently darko uses vanilla fs.watch API which isn't widely supported across platforms. To be honest I haven't tested `--watch` on windows myself. I'll switch to chokidar and see if that will solve this problem.
